abbr -a -- gs 'git status'
abbr -a -- fb 'fzf --preview "bat  --color=always --style=header,grid --line-range :100 {}"'
abbr -a -- ga 'git add .'
abbr -a -- gf 'git fetch'
abbr -a -- gp 'git pull'
abbr -a -- ll 'exa -l -g --icons'
